Updated docstrings
INCATools/PandaSaurus pull request #11
Opened 2023-05-04 07:48 UTC by ubyndr

Draft

2023-05-04 08:20 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +    """Query class is responsible for generating a Pandas dataframe that enriches the seed list with synonyms and
```suggestion
    """Query class is responsible for generating a pandas DataFrame that enriches the seed list with synonyms and
```

2023-05-04 08:20 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +    all inferred subClassOf relationships between terms in the seed. It also allows queries over the dataframe.
```suggestion
    all inferred subClassOf relationships between terms in the seed. It also allows queries over the DataFrame.
```

2023-05-04 08:21 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +        enriched_df (str): Dataframe that is enriched with synonyms and inferred relationships between terms in
```suggestion
        enriched_df (str): DataFrame that is enriched with synonyms and inferred relationships between terms in
```

2023-05-04 08:23 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +        seed list with synonyms and all inferred subClassOf relationships; by default, and it supports other
```suggestion
        seed list with synonyms and all inferred subClassOf relationships by default, and it supports other
```

2023-05-04 08:25 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +            enrichment_property_list (List[str]): Property list to extend enrichment queries.
```suggestion
            enrichment_property_list (List[str]): Property list to extend enrichment queries
```

2023-05-04 08:26 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +        """Returns a Dataframe that is enriched with synonyms and inferred relationships between terms in the seed.
```suggestion
        """Returns a DataFrame that is enriched with synonyms and inferred relationships between terms in the seed.
```

2023-05-04 08:28 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +             pd.Dataframe: Enriched Dataframe
```suggestion
             pd.Dataframe: Enriched DataFrame
```

2023-05-04 08:29 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +        """Returns a Dataframe that is enriched with synonyms and inferred relationships between terms in the seed list
```suggestion
        """Returns a DataFrame that is enriched with synonyms and inferred relationships between terms in the seed list
```

2023-05-04 08:30 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +        """Returns a Dataframe that is enriched with synonyms and inferred relationships between terms in the seed list
```suggestion
        """Returns a DataFrame that is enriched with synonyms and inferred relationships between terms in the seed list
```

2023-05-04 08:31 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +             pd.Dataframe: Enriched Dataframe
```suggestion
             pd.Dataframe: Enriched DataFrame
```

2023-05-04 08:31 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +        """Returns a Dataframe that is enriched with synonyms and inferred relationships between terms in the seed list
```suggestion
        """Returns a DataFrame that is enriched with synonyms and inferred relationships between terms in the seed list
```

2023-05-04 08:31 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +        satisfied by some set of existential restrictions in the ubergraph (e.g. part_of 'Kidney').
```suggestion
        satisfied by some set of existential restrictions in the ubergraph (e.g. part_of 'kidney').
```

2023-05-04 08:32 UTC, bvarner-ebi commented on src/pandasaurus/query.py
> +            pd.Dataframe: Enriched Dataframe
```suggestion
            pd.Dataframe: Enriched DataFrame
```

2023-05-04 08:32 UTC, bvarner-ebi approved these changes
Please see inline suggestions.

2023-05-04 18:22 UTC, dosumis requested changes
Some minor tweaks.  Then happy to merge.

2023-05-04 18:22 UTC, dosumis commented on src/pandasaurus/query.py
> +            slim_list: Slim list that consists of classes tagged with some specified ‘subset’ axiom
slim list = list 'subset' tags.  this makes is sound like a list of IDs

2023-05-04 18:22 UTC, dosumis commented on src/pandasaurus/query.py
> +            enrichment_property_list: Property list to extend enrichment queries. Defaults to None
In standard Python terminology, the second argument is a KWARG (keyword argument).  That it defaults to `None` is an internal implementation issue and would not normally be mentioned.

2023-05-05 11:04 UTC, dosumis approved these changes

2023-05-05 11:07 UTC, merged